sudo: false
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
  - 8
before_script:
  - npm run es5ify
  - npm prune
after_success:
  # publish to npmjs and create a GH release; auto-detects master branch pushes and acts on them only
  - npm run semantic-release
  # manually detect master branch push, and post a dockerhub trigger to build the docker images
  - 'if [ "$TRAVIS_BRANCH" = "master" ]; then curl -s -H "Content-Type: application/json" --data "{\"build\": true}" -X POST https://registry.hub.docker.com/u/snyk/broker/trigger/${DOCKER_TOKEN}/; fi'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
