sudo: false
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
  - 8
before_script:
  - npm run es5ify
  - npm prune
after_success:
  - npm run semantic-release
  - 'curl -s -H "Content-Type: application/json" --data "{\"build\": true}" -X POST https://registry.hub.docker.com/u/snyk/broker/trigger/${DOCKER_TOKEN}/'
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
